// Auto-generated by Electro codegen. Do not edit.
// Feature context types — provides IDE completions for getService/getTask/getFeature.

export {};

/* ── Utility types ────────────────────────────────────── */
type _SvcApi<T> = T extends { api(): infer R } ? NonNullable<R> : never;
type _TaskPayload<T> = T extends { start(payload?: infer P): any } ? P : void;
type _EventPayload<T> = T extends { payload(): infer P } ? P : unknown;

declare module "@cordy/electro" {
    interface FeatureMap {
        "settings": {
            services: {
                "store": _SvcApi<typeof import("./runtime/features/settings/services/store").storeService>;
                "settings": _SvcApi<typeof import("./runtime/features/settings/services/settings").settingsPublicService>;
                "defaults": _SvcApi<typeof import("./runtime/features/settings/services/defaults").defaultsService>;
            };
            tasks: {};
            events: {
                "loaded": _EventPayload<typeof import("./runtime/features/settings/events/loaded").loadedEvent>;
            };
            dependencies: "app-core";
        };
        "window-controls": {
            services: {
                "controls": _SvcApi<typeof import("./runtime/features/window-controls/services/controls-service").controlsService>;
            };
            tasks: {};
            events: {};
            dependencies: "app-core" | "settings";
        };
        "app-core": {
            services: {};
            tasks: {};
            events: {
                "ready": _EventPayload<typeof import("./runtime/features/app-core/events/ready").readyEvent>;
            };
            dependencies: never;
        };
        "sync": {
            services: {};
            tasks: {
                "data-sync": _TaskPayload<typeof import("./runtime/features/sync/tasks/data-sync").dataSyncTask>;
                "health-check": _TaskPayload<typeof import("./runtime/features/sync/tasks/health-check").healthCheckTask>;
                "unreliable-api": _TaskPayload<typeof import("./runtime/features/sync/tasks/unreliable-api").unreliableApiTask>;
            };
            events: {};
            dependencies: "app-core" | "window-controls" | "settings";
        };
        "analytics": {
            services: {};
            tasks: {};
            events: {};
            dependencies: "app-core";
        };
    }

    interface ServiceOwnerMap {
        "store": "settings";
        "settings": "settings";
        "defaults": "settings";
        "controls": "window-controls";
    }

    interface TaskOwnerMap {
        "data-sync": "sync";
        "health-check": "sync";
        "unreliable-api": "sync";
    }

    interface WindowMap {
        "main": import("electron").BrowserWindow;
    }
}
